|WIP| Ban method
New-Voxed/voxed4 pull request #55
Opened 2021-04-19 01:20 UTC by igruntplay

| WORK IN PROGRESS |

Coding ban method.

The idea is find the userIP from firestore and append it to the blacklist.json

2021-04-24 00:36 UTC, rufiandev requested changes

2021-04-24 00:36 UTC, rufiandev commented on server/index.js
> +  let search = await firebase.db.collection("users").where('userId','==', req.body.userId).get();
aca se puede usar directamente el userID de la linea de arriba sin tener que poner req.body y el 'userId' deberia ser 'userID' con D mayuscula asi coincide con el de firestore

2021-04-24 00:36 UTC, rufiandev commented on server/index.js
> +  fs.appendFile("/blacklist-historic.json",`'\n'${search.data().userIP}`, (error)=>{
esto no creo que ande porque el historico tiene este formato
```
{
  "ips": ["192.168.0.1", "192.168.0.2", "192.168.0.3", "192.168.0.4"]
}
```
y si le appendeas de esta forma va a quedar asi

```
{
  "ips": ["192.168.0.1", "192.168.0.2", "192.168.0.3", "192.168.0.4"]
}'\n'192.168.1.1

```

2021-04-24 00:50 UTC, igruntplay commented on server/index.js
> +  fs.appendFile("/blacklist-historic.json",`'\n'${search.data().userIP}`, (error)=>{
Eee Perá, esto del FS escribilo vos acáy lo pusheo

2021-04-24 00:59 UTC, rufiandev commented on server/index.js
> +  fs.appendFile("/blacklist-historic.json",`'\n'${search.data().userIP}`, (error)=>{
fs.open('/blacklist-historic.json', 'w+', function (err, f) {
  if (err) {
     return console.error(err);
  }

  const bans = JSON.parse(f);
  bans.ips.push(search.data().userIP);
});

2021-04-24 01:00 UTC, rufiandev commented on server/index.js
> +  fs.appendFile("/blacklist-historic.json",`'\n'${search.data().userIP}`, (error)=>{
```
fs.open('/blacklist-historic.json', 'w+', function (err, f) {
  if (err) {
     return console.error(err);
  }

  const bans = JSON.parse(f);
  bans.ips.push(search.data().userIP);
});
```

no lo probe xd

2021-04-24 01:08 UTC, igruntplay commented on server/index.js
> +  fs.appendFile("/blacklist-historic.json",`'\n'${search.data().userIP}`, (error)=>{
veni discord puto

2021-04-25 23:52 UTC, igruntplay commented on server/index.js
> +  fs.open('/blacklist-historic.json', 'w+', function (err, f) {
@rufiandev

2021-04-26 01:10 UTC, rufiandev approved these changes

2021-04-26 01:42 UTC, merged