Fix: responsive, green text, time, embed links
New-Voxed/voxed4 pull request #73
Opened 2021-06-09 20:57 UTC by martnpz

> Add: >>Link text.
> Add: YouTube Embed in comments.
> Fix: green text.
> Fix: responsive:
> Change: Date in comments to local date es-AR.
> Change: img tag for posts.

2021-06-13 19:28 UTC, igruntplay requested changes
@rufiandev Revisá que esto esté bien.

@martnpz a vos te compilaba bien? va bien?
Sí podés agregar fotos y/o videos al pr taria piola

2021-06-13 19:28 UTC, igruntplay commented on init.sh
> +set -o nounset
Hola, pls eliminá esto del PR.
Es solo una extensión del docker, no hay necesidad de modificarlo por ahora.

2021-06-13 22:07 UTC, igruntplay approved these changes
Por mí está bien, pero lo tiene que mirar @rufiandev a ver si el front a nivel código está bien XD.
Esperemos que dice.

2021-06-14 12:34 UTC, rufiandev approved these changes
lo veo bien

2021-06-14 12:35 UTC, merged